/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tunisianwatch.Gui;

/**
 *
 * @author asd
 */
public class AddCommentairePanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCommentairePanel
     */
    public AddCommentairePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentaireTextArea = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(762, 196));

        addButton.setBackground(new java.awt.Color(204, 0, 0));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Commenter");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(166, 96));

        commentaireTextArea.setEditable(false);
        commentaireTextArea.setColumns(20);
        commentaireTextArea.setForeground(new java.awt.Color(102, 102, 102));
        commentaireTextArea.setTabSize(0);
        commentaireTextArea.setText("Ajouter un Commentaire");
        commentaireTextArea.setMinimumSize(new java.awt.Dimension(164, 94));
        commentaireTextArea.setPreferredSize(new java.awt.Dimension(164, 94));
        commentaireTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentaireTextAreaMouseClicked(evt);
            }
        });
        commentaireTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                commentaireTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(commentaireTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void commentaireTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commentaireTextAreaKeyReleased

    }//GEN-LAST:event_commentaireTextAreaKeyReleased

    private void commentaireTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentaireTextAreaMouseClicked
        commentaireTextArea.setForeground(new java.awt.Color(0,0,0));
        commentaireTextArea.setText("");
        commentaireTextArea.setEditable(true);
    }//GEN-LAST:event_commentaireTextAreaMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea commentaireTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
