/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunisianwatch.Gui;

import com.tunisianwatch.Dao.UtilisateurDao;
import com.tunisianwatch.Entities.Utilisateur;
import javax.swing.JOptionPane;

/**
 *
 * @author Khadija
 */
public class InscriPanel extends javax.swing.JPanel {

    /**
     * Creates new form InscriPanel
     */
    public InscriPanel() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrénom = new javax.swing.JLabel();
        jLabelMdp = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelConfirmerMDP = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelDateNaissance = new javax.swing.JLabel();
        textFieldNom = new java.awt.TextField();
        textFieldPrénom = new java.awt.TextField();
        textFieldEmail = new java.awt.TextField();
        textFieldAdresse = new java.awt.TextField();
        textFieldLogin = new java.awt.TextField();
        textFieldMdp = new java.awt.TextField();
        textFieldConfirmerMdp = new java.awt.TextField();
        jComboBoxSexe = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        buttonValider = new java.awt.Button();
        jLabelVide = new javax.swing.JLabel();
        jLabelCMdp = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(237, 237, 237));
        jPanel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabelNom.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelNom.setText("Nom:");

        jLabelPrénom.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelPrénom.setText("Prénom");

        jLabelMdp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelMdp.setText("Mot de passe");

        jLabelLogin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelLogin.setText("Login");

        jLabelConfirmerMDP.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelConfirmerMDP.setText("Confirmer");

        jLabelAdresse.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelAdresse.setText("Adresse");

        jLabelSexe.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelSexe.setText("Civilité:");

        jLabelEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelDateNaissance.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelDateNaissance.setText("Date de Naissance");

        textFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomActionPerformed(evt);
            }
        });

        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        textFieldMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMdpActionPerformed(evt);
            }
        });

        textFieldConfirmerMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldConfirmerMdpActionPerformed(evt);
            }
        });

        jComboBoxSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(226, 31, 31));
        jLabel2.setText("Inscription");
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 50));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));

        buttonValider.setBackground(new java.awt.Color(249, 26, 26));
        buttonValider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonValider.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonValider.setForeground(new java.awt.Color(255, 255, 255));
        buttonValider.setLabel("Valider");
        buttonValider.setName("Valider"); // NOI18N
        buttonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderActionPerformed(evt);
            }
        });

        jLabelVide.setBackground(new java.awt.Color(204, 0, 0));
        jLabelVide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelVide.setForeground(new java.awt.Color(204, 0, 0));

        jLabelCMdp.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelVide, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(190, 190, 190)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(textFieldConfirmerMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelCMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAdresse)
                            .addComponent(jLabelMdp)
                            .addComponent(jLabelConfirmerMDP)
                            .addComponent(jLabelDateNaissance)
                            .addComponent(jLabelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrénom)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelEmail)
                                .addComponent(jLabelLogin)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrénom)
                            .addComponent(textFieldPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLogin))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMdp))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelConfirmerMDP)
                            .addComponent(textFieldConfirmerMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDateNaissance))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVide, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonValider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelNom)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tunisianwatch/Images/tw_logo_74x165.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoLabel)
                .addGap(724, 724, 724))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldConfirmerMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldConfirmerMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldConfirmerMdpActionPerformed

    private void buttonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderActionPerformed
        // TODO add your handling code here:
        Utilisateur user = new Utilisateur();
        UtilisateurDao userDao = new UtilisateurDao();

        user.setSexe(jComboBoxSexe.getSelectedItem().toString().charAt(0));
        user.setNom(textFieldNom.getText());
        user.setPrenom(textFieldPrénom.getText());
        user.setLogin(textFieldLogin.getText());
        user.setAdress(textFieldAdresse.getText());
        user.setMail(textFieldEmail.getText());
        user.setMdp(textFieldMdp.getText());
        user.setDateNaissance(jDateChooser1.getDate());
     //   if ((textFieldLogin.getText().length() != 0) && (textFieldAdresse.getText().length() != 0) && (textFieldMdp.getText().length() != 0) && (textFieldConfirmerMdp.getText() == textFieldMdp.getText()) && ((textFieldEmail).getText().toString().matches("^[a-zA-Z0-9\\.\\-\\_]+@([a-zA-Z0-9\\-\\_\\.]+\\.)+([a-zA-Z]{2,4})$")) && (textFieldNom.getText().length() != 0) && (textFieldPrénom.getText().length() != 0) && (jDateChooser1.getDate().getYear() <= 2002)) {

            if (userDao.insertUser(user) > 0) {
                JOptionPane.showMessageDialog(null, "Ajout effectuée avec succès");
            } else {
                JOptionPane.showMessageDialog(null, "Erreur lors de l'insertion");
            }
  //      }
//        else if ((textFieldConfirmerMdp.getText() != textFieldMdp.getText())&&(textFieldLogin.getText().length() != 0) &&(textFieldAdresse.getText().length() != 0)  && (textFieldMdp.getText().length() != 0)&& ((textFieldEmail).getText().toString().matches("^[a-zA-Z0-9\\.\\-\\_]+@([a-zA-Z0-9\\-\\_\\.]+\\.)+([a-zA-Z]{2,4})$")) && (textFieldNom.getText().length() != 0) && (textFieldPrénom.getText().length() != 0) && (jDateChooser1.getDate().getYear() <= 2002)) {
//         jLabelCMdp.setText("le mot de passe n'est pas identique !");
//
//         } else if (!textFieldEmail.getText().toString().matches("^[a-zA-Z0-9\\.\\-\\_]+@([a-zA-Z0-9\\-\\_\\.]+\\.)+([a-zA-Z]{2,4})$")&&(textFieldLogin.getText().length() != 0) &&(textFieldAdresse.getText().length() != 0)  && (textFieldMdp.getText().length() != 0) && (textFieldConfirmerMdp.getText() == textFieldMdp.getText()) && (textFieldNom.getText().length() != 0) && (textFieldPrénom.getText().length() != 0) && (jDateChooser1.getDate().getYear() <= 2002)) {
//           jLabel1.setText("Ça ne semble pas être un email valide!");
//        } else {
//          jLabelVide.setText("Vous devez remplir tout les champs correctement!");
//        }
    }//GEN-LAST:event_buttonValiderActionPerformed

    private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailActionPerformed

    private void textFieldMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMdpActionPerformed

    private void textFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonValider;
    private javax.swing.JComboBox jComboBoxSexe;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelCMdp;
    private javax.swing.JLabel jLabelConfirmerMDP;
    private javax.swing.JLabel jLabelDateNaissance;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMdp;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrénom;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JLabel jLabelVide;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoLabel;
    private java.awt.TextField textFieldAdresse;
    private java.awt.TextField textFieldConfirmerMdp;
    private java.awt.TextField textFieldEmail;
    private java.awt.TextField textFieldLogin;
    private java.awt.TextField textFieldMdp;
    private java.awt.TextField textFieldNom;
    private java.awt.TextField textFieldPrénom;
    // End of variables declaration//GEN-END:variables
}
