/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunisianwatch.Gui;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author asd
 */
public class MainFrame extends javax.swing.JFrame {

    public static int id;
    private static MainFrame mainFrameInstance;
    private static char type;

    /**
     * Creates new form MainFrame
     */
    public static MainFrame getInstance(int id, char type) {
        setType(type);
        setId(id);
        if (mainFrameInstance == null) {
            mainFrameInstance = new MainFrame();
        }
        return mainFrameInstance;
    }

    public static MainFrame getInstance() {
        if (mainFrameInstance == null) {
            mainFrameInstance = new MainFrame();
        }
        return mainFrameInstance;
    }

    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        MainFrame.id = id;
    }

    public static void setType(char type) {
        MainFrame.type = type;
    }

    private MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        if (type == 'A') {
            this.add(new AcceuilPanel());
        } else {
            this.add(new ClientAcceuilPanel());
        }
        /* contentPanel.removeAll();
         contentPanel.add(new ProfilPanel());
         contentPanel.repaint();
         contentPanel.revalidate();*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tunisianwatch");
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
