/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tunisianwatch.Gui;

import com.tunisianwatch.Entities.Reclamation;

/**
 *
 * @author asd
 */
public class ReclamationApercuPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReclamationApercuPanel
     */
    public ReclamationApercuPanel(Object o) {
        initComponents();
        Reclamation r = (Reclamation) o;
        titreTextField.setText(r.getTitre());
        citoyenTextField.setText(r.getCitoyen().getPrenom()+" "+r.getCitoyen().getNom());
        dateTextField.setText(r.getDate().toString()+" "+r.getHeure());
        lieuTextField.setText(r.getLieu().getNom());
        if(r.getEtat()==0){
            etatTextField.setText("Pas encore Réglée");
        }
        else if(r.getEtat()==1){
            etatTextField.setText("Réglée");
        }
        else if(r.getEtat()==2){
            etatTextField.setText("Fausse");
        }
       domaineTextField.setText(r.getDomaine().getNom());
       descriptionTextArea.setText(r.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreTextField = new javax.swing.JTextField();
        titreLabel = new javax.swing.JLabel();
        lieuLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        domaineLabel = new javax.swing.JLabel();
        citoyenLabel = new javax.swing.JLabel();
        etatLabel = new javax.swing.JLabel();
        lieuTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        dateTextField = new javax.swing.JTextField();
        domaineTextField = new javax.swing.JTextField();
        etatTextField = new javax.swing.JTextField();
        citoyenTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(870, 500));
        setPreferredSize(new java.awt.Dimension(870, 500));

        titreTextField.setEditable(false);
        titreTextField.setBackground(new java.awt.Color(204, 204, 204));

        titreLabel.setText("Titre");

        lieuLabel.setText("Lieu");

        dateLabel.setText("Date");

        domaineLabel.setText("Domaine");

        citoyenLabel.setText("Citoyen");

        etatLabel.setText("Etat");

        lieuTextField.setEditable(false);
        lieuTextField.setBackground(new java.awt.Color(204, 204, 204));
        lieuTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lieuTextFieldActionPerformed(evt);
            }
        });

        descriptionLabel.setText("Description");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setBackground(new java.awt.Color(204, 204, 204));
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        ScrollPane.setViewportView(descriptionTextArea);

        dateTextField.setEditable(false);
        dateTextField.setBackground(new java.awt.Color(204, 204, 204));
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        domaineTextField.setEditable(false);
        domaineTextField.setBackground(new java.awt.Color(204, 204, 204));
        domaineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domaineTextFieldActionPerformed(evt);
            }
        });

        etatTextField.setEditable(false);
        etatTextField.setBackground(new java.awt.Color(204, 204, 204));
        etatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etatTextFieldActionPerformed(evt);
            }
        });

        citoyenTextField.setEditable(false);
        citoyenTextField.setBackground(new java.awt.Color(204, 204, 204));
        citoyenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citoyenTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addGap(45, 45, 45)
                        .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(domaineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(domaineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lieuLabel)
                            .addComponent(titreLabel))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lieuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(citoyenLabel)
                            .addComponent(etatLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(citoyenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titreLabel))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lieuLabel)
                            .addComponent(lieuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLabel)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(domaineLabel)
                            .addComponent(domaineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etatLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(citoyenLabel)
                            .addComponent(citoyenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lieuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lieuTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lieuTextFieldActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void domaineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domaineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domaineTextFieldActionPerformed

    private void etatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etatTextFieldActionPerformed

    private void citoyenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citoyenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citoyenTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel citoyenLabel;
    private javax.swing.JTextField citoyenTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel domaineLabel;
    private javax.swing.JTextField domaineTextField;
    private javax.swing.JLabel etatLabel;
    private javax.swing.JTextField etatTextField;
    private javax.swing.JLabel lieuLabel;
    private javax.swing.JTextField lieuTextField;
    private javax.swing.JLabel titreLabel;
    private javax.swing.JTextField titreTextField;
    // End of variables declaration//GEN-END:variables
}
