/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunisianwatch.Gui;

import com.tunisianwatch.Dao.ChartDAO;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author DELL
 */
public class StatistiquePanel extends javax.swing.JPanel {

    /**
     * Creates new form StatistiquePanel
     */
    
    public void AjouterChartpanelCercelDomaine(String titre) {
        contentPanel.removeAll();
        ChartPanel panel = new ChartPanel(ChartDAO.createChartdomaine(titre));
        panel.setBounds(10, 10, (int) contentPanel.getSize().getWidth()-20, (int)contentPanel.getSize().getHeight()-20);
        contentPanel.add(panel);
        contentPanel.repaint();
    }

    public void AjouterChartpanelBarDomaine(String titre, String axeX, String axeY) {
        contentPanel.removeAll();
        ChartPanel panel = new ChartPanel(ChartDAO.createBarchartDomaine(titre, axeX, axeY));
        panel.setBounds(10, 10, (int) contentPanel.getSize().getWidth()-20, (int)contentPanel.getSize().getHeight()-20);
        contentPanel.add(panel);
        contentPanel.repaint();
    }

    public void AjouterChartpanelCercelLieu(String titre) {
        contentPanel.removeAll();
        ChartPanel panel = new ChartPanel(ChartDAO.createChartLieu(titre));
        panel.setBounds(10, 10, (int) contentPanel.getSize().getWidth()-20, (int)contentPanel.getSize().getHeight()-20);
        contentPanel.add(panel);
        contentPanel.repaint();
    }

    public void AjouterChartpanelBarLieu(String titre, String axeX, String axeY) {
        contentPanel.removeAll();
        ChartPanel panel = new ChartPanel(ChartDAO.Createbarchartlieu(titre, axeX, axeY));
        panel.setBounds(10, 10, (int) contentPanel.getSize().getWidth()-20, (int)contentPanel.getSize().getHeight()-20);
        contentPanel.add(panel);
        contentPanel.repaint();
    }

    public void AjouterChartpanelCercelEtat(String titre) {
        contentPanel.removeAll();
        ChartPanel panel = new ChartPanel(ChartDAO.createChartEtat(titre));
        panel.setBounds(10, 10, (int) contentPanel.getSize().getWidth()-20, (int)contentPanel.getSize().getHeight()-20);
        contentPanel.add(panel);
        contentPanel.repaint();
    }

    public void AjouterChartpanelBarEtat(String titre, String axeX, String axeY) {
        contentPanel.removeAll();
        ChartPanel panel = new ChartPanel(ChartDAO.createBarchartEtat(titre, axeX, axeY));
        panel.setBounds(10, 10, (int) contentPanel.getSize().getWidth()-20, (int)contentPanel.getSize().getHeight()-20);
        contentPanel.add(panel);
        contentPanel.repaint();
    }

    public StatistiquePanel() {
        initComponents();
         AjouterChartpanelCercelDomaine("Statistique par Domaines");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        comboName = new javax.swing.JComboBox();
        ComboType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Statistiques des Réclamations"));

        comboName.setBackground(new java.awt.Color(204, 0, 0));
        comboName.setForeground(new java.awt.Color(255, 255, 255));
        comboName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domaine", "Etat", "Lieu" }));
        comboName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNameActionPerformed(evt);
            }
        });

        ComboType.setBackground(new java.awt.Color(204, 0, 0));
        ComboType.setForeground(new java.awt.Color(255, 255, 255));
        ComboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pie chart 3D", "Bar chart 3D" }));
        ComboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Génération :");

        jLabel2.setText("Type de Graphe");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNameActionPerformed
        // TODO add your handling code here:
        if (comboName.getSelectedIndex() == 0) {//domaine
            if (ComboType.getSelectedIndex() == 0) {
                //piechart3D
                AjouterChartpanelCercelDomaine("Statistique par Domaines");
            } else {
                //barchar3D
                AjouterChartpanelBarDomaine("Statistique par Domaines", "Domaines", "Frequence des Reclamations");
            }

        } else {
            if (comboName.getSelectedIndex() == 1) {//etat
                if (ComboType.getSelectedIndex() == 0) {
                    //piechart3D
                    AjouterChartpanelCercelEtat("Statistique par Etat");
                } else {
                    if (comboName.getSelectedIndex()==3)//barchar3D
                        AjouterChartpanelBarEtat("Statistique par Etat", "Etat", "Frequence des Reclamation");
                }
            } else {//lieu
                if (ComboType.getSelectedIndex() == 0) {//piechart3D
                    AjouterChartpanelCercelLieu("Statistique par Lieu");
                } else {//barchar3D
                    AjouterChartpanelBarLieu("Statistique par Lieu", "Les lieus", "Frequence des Reclamtions");
                }
            }
        }
    }//GEN-LAST:event_comboNameActionPerformed

    private void ComboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTypeActionPerformed
        // TODO add your handling code here:
        if (comboName.getSelectedIndex() == 0) {//domaine
            if (ComboType.getSelectedIndex() == 0) {
                //piechart3D
                AjouterChartpanelCercelDomaine("Statistique par Domaines");
            } else {
                //barchar3D
                AjouterChartpanelBarDomaine("Statistique par Domaines", "Domaines", "Frequence des Reclamations");
            }

        } else {
            if (comboName.getSelectedIndex() == 1) {//etat
                if (ComboType.getSelectedIndex() == 0) {
                    //piechart3D
                    AjouterChartpanelCercelEtat("Statistique par Etat");
                } else {
                    //barchar3D
                    AjouterChartpanelBarEtat("Statistique par Etat", "Etat", "Frequence des Reclamation");
                }
            } else {//lieu
                if (ComboType.getSelectedIndex() == 0) {//piechart3D
                    AjouterChartpanelCercelLieu("Statistique par Lieu");
                } else {//barchar3D
                    AjouterChartpanelBarLieu("Statistique par Lieu", "Les lieus", "Frequence des Reclamtions");
                }
            }
        }
    }//GEN-LAST:event_ComboTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboType;
    private javax.swing.JComboBox comboName;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
